import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { useParams, Link } from "react-router-dom";
import type { Id } from "../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Star, Database, Clock, HardDrive, Zap, Shield, TrendingUp,
  Copy, Download, ArrowLeft, Loader2, FlaskConical, Brain, Code
} from "lucide-react";
import { toast } from "sonner";

export function SolutionDetailPage() {
  const { solutionId } = useParams();
  const solution = useQuery(api.solutions.getSolution, solutionId ? { id: solutionId as Id<"solutions"> } : "skip");

  if (!solution) {
    return (
      <div className="flex items-center justify-center h-96 text-muted-foreground">
        <Loader2 className="size-5 animate-spin mr-2" /> Loading solution...
      </div>
    );
  }

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard!`);
  };

  const downloadSchema = (content: string, filename: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link to={`/results/${solution.analysisRunId}`}>
            <Button variant="ghost" size="sm">
              <ArrowLeft className="size-4 mr-1" /> Back to Results
            </Button>
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-bold tracking-tight">Solution #{solution.solutionIndex + 1}</h1>
              {solution.isPareto && (
                <Badge className="bg-emerald-500/10 text-emerald-500 border-emerald-500/30">
                  <Star className="size-3 mr-1" /> Pareto Optimal
                </Badge>
              )}
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              Generated by {solution.algorithm} · Confidence {(solution.confidence * 100).toFixed(0)}%
            </p>
          </div>
        </div>
        <Link to="/simulation">
          <Button className="bg-emerald-600 hover:bg-emerald-700">
            <FlaskConical className="size-4 mr-2" /> Run Simulation
          </Button>
        </Link>
      </div>

      {/* Metrics cards */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {[
          { label: "Insertion Time", value: `${solution.metrics.insertionTime.toFixed(1)} ms`, icon: Zap, color: "text-blue-500" },
          { label: "Query Time", value: `${solution.metrics.queryTime.toFixed(1)} ms`, icon: Clock, color: "text-purple-500" },
          { label: "Storage Size", value: solution.metrics.storageSize > 1000 ? `${(solution.metrics.storageSize / 1000).toFixed(1)} KB` : `${solution.metrics.storageSize} B`, icon: HardDrive, color: "text-amber-500" },
          { label: "Security", value: `${((solution.metrics.securityScore ?? 0.8) * 100).toFixed(0)}%`, icon: Shield, color: "text-emerald-500" },
          { label: "Scalability", value: `${((solution.metrics.scalabilityScore ?? 0.75) * 100).toFixed(0)}%`, icon: TrendingUp, color: "text-cyan-500" },
        ].map(m => (
          <Card key={m.label}>
            <CardContent className="pt-4 pb-3 px-4">
              <div className="flex items-center gap-2 text-muted-foreground mb-1">
                <m.icon className={`size-3.5 ${m.color}`} />
                <span className="text-xs">{m.label}</span>
              </div>
              <span className="text-lg font-bold">{m.value}</span>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {/* Mapping Strategies */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Database className="size-4 text-emerald-500" />
              Inheritance Mapping Strategies
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {solution.mappingStrategies.map((m: { className: string; strategy: string }) => (
                <div key={m.className} className="flex items-center justify-between py-2 border-b border-border/40 last:border-0">
                  <span className="font-medium text-sm">{m.className}</span>
                  <StrategyBadge strategy={m.strategy} />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Association Strategies */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Brain className="size-4 text-blue-500" />
              Association Mapping Strategies
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {solution.associationStrategies.map((a: { associationName: string; strategy: string }) => (
                <div key={a.associationName} className="flex items-center justify-between py-2 border-b border-border/40 last:border-0">
                  <span className="font-medium text-sm truncate mr-2">{a.associationName}</span>
                  <StrategyBadge strategy={a.strategy} />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Schema Output */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Code className="size-5 text-emerald-500" />
            Generated Database Schema
          </CardTitle>
          <CardDescription>
            Deployable schema in SQL and NoSQL formats
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="sql">
            <div className="flex items-center justify-between mb-3">
              <TabsList>
                <TabsTrigger value="sql">SQL (MySQL)</TabsTrigger>
                <TabsTrigger value="nosql">NoSQL (MongoDB)</TabsTrigger>
              </TabsList>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => copyToClipboard(solution.sqlSchema || "", "SQL Schema")}
                >
                  <Copy className="size-3.5 mr-1" /> Copy
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => downloadSchema(
                    solution.sqlSchema || "",
                    `solution_${solution.solutionIndex + 1}.sql`
                  )}
                >
                  <Download className="size-3.5 mr-1" /> Download
                </Button>
              </div>
            </div>
            <TabsContent value="sql">
              <pre className="bg-muted/50 border rounded-lg p-4 overflow-x-auto text-xs font-mono leading-relaxed max-h-[500px] overflow-y-auto">
                {solution.sqlSchema || "No SQL schema generated"}
              </pre>
            </TabsContent>
            <TabsContent value="nosql">
              <pre className="bg-muted/50 border rounded-lg p-4 overflow-x-auto text-xs font-mono leading-relaxed max-h-[500px] overflow-y-auto">
                {solution.nosqlSchema || "No NoSQL schema generated"}
              </pre>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Roadmap */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="size-5 text-amber-500" />
            Performance Roadmap
          </CardTitle>
          <CardDescription>
            Expected software performance implications for this design
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {getRoadmapItems(solution).map((item, i) => (
              <div key={i} className="flex gap-4">
                <div className={`size-8 rounded-full flex items-center justify-center shrink-0 ${item.bgColor}`}>
                  <span className="text-xs font-bold">{i + 1}</span>
                </div>
                <div>
                  <h4 className="font-medium text-sm">{item.title}</h4>
                  <p className="text-xs text-muted-foreground mt-0.5">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function StrategyBadge({ strategy }: { strategy: string }) {
  const config: Record<string, { label: string; color: string }> = {
    UnionSubclass: { label: "Union Subclass", color: "bg-blue-500/10 text-blue-500 border-blue-500/30" },
    JoinedSubclass: { label: "Joined Subclass", color: "bg-purple-500/10 text-purple-500 border-purple-500/30" },
    UnionSuperclass: { label: "Union Superclass", color: "bg-amber-500/10 text-amber-500 border-amber-500/30" },
    ForeignKeyEmbedding: { label: "FK Embedding", color: "bg-emerald-500/10 text-emerald-500 border-emerald-500/30" },
    OwnAssociationTable: { label: "Own Table", color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/30" },
  };
  const c = config[strategy] || { label: strategy, color: "" };
  return <Badge variant="outline" className={`text-xs ${c.color}`}>{c.label}</Badge>;
}

function getRoadmapItems(solution: any) {
  if (!solution) return [];
  const hasJoined = solution.mappingStrategies.some((m: any) => m.strategy === "JoinedSubclass");
  const hasUnionSuper = solution.mappingStrategies.some((m: any) => m.strategy === "UnionSuperclass");
  const hasFK = solution.associationStrategies.some((a: any) => a.strategy === "ForeignKeyEmbedding");
  const hasOwnTable = solution.associationStrategies.some((a: any) => a.strategy === "OwnAssociationTable");
  const queryTime = solution.metrics.queryTime;
  const insertTime = solution.metrics.insertionTime;

  const items = [];

  if (queryTime < 3) {
    items.push({
      title: "Excellent Query Performance",
      desc: "This schema is optimized for fast reads. Ideal for read-heavy workloads like dashboards, reporting, and analytics.",
      bgColor: "bg-emerald-500/20 text-emerald-500",
    });
  } else {
    items.push({
      title: "Balanced Query Performance",
      desc: "Query performance is acceptable. Consider adding indexes on frequently queried columns for further optimization.",
      bgColor: "bg-amber-500/20 text-amber-500",
    });
  }

  if (hasJoined) {
    items.push({
      title: "Normalized Structure — Lower Storage, More Joins",
      desc: "JoinedSubclass strategy reduces data redundancy but requires JOIN operations. Use connection pooling and query caching to mitigate latency.",
      bgColor: "bg-blue-500/20 text-blue-500",
    });
  }

  if (hasUnionSuper) {
    items.push({
      title: "Consolidated Tables — Simple Queries, NULL Columns",
      desc: "UnionSuperclass uses single tables with discriminator columns. Queries are simpler but tables may have many NULL fields. Good for polymorphic queries.",
      bgColor: "bg-purple-500/20 text-purple-500",
    });
  }

  if (hasOwnTable) {
    items.push({
      title: "Junction Tables for Many-to-Many",
      desc: "Own association tables provide clear many-to-many relationships. Index both foreign key columns for optimal join performance.",
      bgColor: "bg-cyan-500/20 text-cyan-500",
    });
  }

  if (hasFK) {
    items.push({
      title: "Embedded Foreign Keys — Fewer Joins",
      desc: "ForeignKeyEmbedding reduces table count and join complexity. Ideal for frequently traversed one-to-many relationships.",
      bgColor: "bg-emerald-500/20 text-emerald-500",
    });
  }

  items.push({
    title: "Scalability Recommendations",
    desc: `At current metrics (insert: ${insertTime.toFixed(1)}ms, query: ${queryTime.toFixed(1)}ms), this design supports moderate-to-high concurrent loads. For production: implement read replicas, connection pooling, and consider partitioning for tables exceeding 10M rows.`,
    bgColor: "bg-orange-500/20 text-orange-500",
  });

  items.push({
    title: "Security Considerations",
    desc: "Apply row-level security policies, parameterized queries to prevent SQL injection, and audit logging on sensitive tables. Schema score: " + ((solution.metrics.securityScore ?? 0.8) * 100).toFixed(0) + "%.",
    bgColor: "bg-red-500/20 text-red-500",
  });

  return items;
}
